### ISSUE TITLE
Model for users does not generate properly anymore

### ISSUE THREAD

**Issue by TilBlechschmidt** [bcongdon/git-trophy#12]
## Bug description
When generating a model for just a user (and not a repository) like `TilBlechschmidt` the site no longer fetches the contributions and outputs an invalid 3D model 😢 

Example: https://gittrophy.com?entity=tilblechschmidt&year=2020
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/5037967/111918362-0ab74b00-8a85-11eb-8fa9-60ce2570659b.png">

## Expected behaviour
Some 3D representation of this
<img width="929" alt="image" src="https://user-images.githubusercontent.com/5037967/111918396-2de1fa80-8a85-11eb-9a4a-1dc337edac72.png">

**Comment by bcongdon** [comment]
Thanks for pointing this out! The issue should be fixed now.
